collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7132617
color:
  saturation: 0.8727599
  brandStrength: 0.8136201
  lightness: 0.2419355
  brandColors:
    - '#424242'
    - '#A39280'
    - '#DFE0CE'
    - '#CFBFA2'
    - '#866333'
  rhythmicContrast: 0.2240143
layout_spectrum: 1
name: Quest4fire
