favicon: null
name: Quest4fire
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.05017921
  rhythmicContrast: 0
  brandColors:
    - '#000000'
    - '#ac9997'
    - '#47524f'
    - '#d2d3e1'
    - '#fefeea'
  lightness: 0.125
typography_spectrum: 0.54266
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
