name: Quest4fire
favicon: null
layout_spectrum: 0.34524
typography_spectrum: 0.54266
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ac9997'
    - '#47524f'
    - '#d2d3e1'
    - '#fefeea'
  brandStrength: 0.05017921
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0
purpose: []
